server:
  port: 8082

spring:
  application:
    name: exercise-service

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    template:
      retry:
        enabled: true
        initial-interval: 3s
        max-attempts: 3

  datasource:
    url: jdbc:postgresql://exercisedb:5432/exercisedb
    username: postgres
    password: ${EXERCISE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/
  instance:
    prefer-ip-address: false