server:
  port: 8080

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}

spring:
  application:
    name: gateway-server
  data:
    redis:
      host: redis
      port: 6379
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # EXERCISE SERVICE
        - id: exercise-service
          uri: lb://exercise-service
          predicates:
            - Path=/api/v1/exercises/**
          filters:
            - name: CircuitBreaker
              args:
                name: exerciseCB
                fallbackUri: forward:/fallback/exercise

        # WORKOUT SERVICE
        - id: workout-service
          uri: lb://workout-service
          predicates:
            - Path=/api/v1/workouts/**
          filters:
            - name: CircuitBreaker
              args:
                name: workoutCB
                fallbackUri: forward:/fallback/workout

        # USER(AUTH) SERVICE
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**, /api/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: userCB
                fallbackUri: forward:/fallback/user

      httpclient:
        connect-timeout: 1000
        response-timeout: 4s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/
  instance:
    prefer-ip-address: true